[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask-migrate>=4.0.7",
    "flask-sqlalchemy",
    "flask>=3.1.0",
    "nicegui>=2.7.0",
    "python-dotenv>=1.0.1",
    "sqlalchemy",
]
